# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.api.fiscalization_api import FiscalizationApi


class TestFiscalizationApi(unittest.TestCase):
    """FiscalizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FiscalizationApi()

    def tearDown(self) -> None:
        pass

    def test_create_fiscalization_consent(self) -> None:
        """Test case for create_fiscalization_consent

        Record user consent for fiscalization
        """
        pass

    def test_create_fiscalization_registration(self) -> None:
        """Test case for create_fiscalization_registration

        Create fiscalization registration
        """
        pass

    def test_get_fiscalization_consent(self) -> None:
        """Test case for get_fiscalization_consent

        Get consent status for a property
        """
        pass

    def test_get_fiscalization_provider(self) -> None:
        """Test case for get_fiscalization_provider

        Get fiscalization provider info for a country
        """
        pass

    def test_get_fiscalization_registration(self) -> None:
        """Test case for get_fiscalization_registration

        Get fiscalization registration for a property
        """
        pass

    def test_get_fiscalization_registration_countries(self) -> None:
        """Test case for get_fiscalization_registration_countries

        Get available countries for property registration
        """
        pass

    def test_get_fiscalization_registration_rules(self) -> None:
        """Test case for get_fiscalization_registration_rules

        Get fiscalization registration rules for a country
        """
        pass

    def test_get_fiscalization_registration_status(self) -> None:
        """Test case for get_fiscalization_registration_status

        Get registration status for a property
        """
        pass

    def test_get_fiscalization_tax(self) -> None:
        """Test case for get_fiscalization_tax

        Get fiscalization tax for a property
        """
        pass

    def test_get_fiscalization_tax_rules(self) -> None:
        """Test case for get_fiscalization_tax_rules

        Get fiscalization tax rules for a country
        """
        pass

    def test_update_fiscalization_registration(self) -> None:
        """Test case for update_fiscalization_registration

        Update fiscalization registration
        """
        pass

    def test_update_fiscalization_tax(self) -> None:
        """Test case for update_fiscalization_tax

        Update fiscalization tax for a property
        """
        pass

    def test_validate_fiscalization_data(self) -> None:
        """Test case for validate_fiscalization_data

        Validate fiscalization registration data
        """
        pass


if __name__ == '__main__':
    unittest.main()
