# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.models.fiscalization_phone import FiscalizationPhone

class TestFiscalizationPhone(unittest.TestCase):
    """FiscalizationPhone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiscalizationPhone:
        """Test FiscalizationPhone
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiscalizationPhone`
        """
        model = FiscalizationPhone()
        if include_optional:
            return FiscalizationPhone(
                number = '+39 02 1234567',
                label = 'Office'
            )
        else:
            return FiscalizationPhone(
                number = '+39 02 1234567',
        )
        """

    def testFiscalizationPhone(self):
        """Test FiscalizationPhone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
