# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.models.transactions_summary_request import TransactionsSummaryRequest

class TestTransactionsSummaryRequest(unittest.TestCase):
    """TransactionsSummaryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionsSummaryRequest:
        """Test TransactionsSummaryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionsSummaryRequest`
        """
        model = TransactionsSummaryRequest()
        if include_optional:
            return TransactionsSummaryRequest(
                document_kind = 'INVOICE',
                source_id = 1,
                source_kind = 'GROUP_PROFILE',
                folio_ids = [
                    56
                    ],
                exclude_transaction_ids = [
                    56
                    ],
                include_transaction_ids = [
                    56
                    ],
                transaction_id_to_amount = {
                    'key' : 1.337
                    }
            )
        else:
            return TransactionsSummaryRequest(
                source_id = 1,
                source_kind = 'GROUP_PROFILE',
        )
        """

    def testTransactionsSummaryRequest(self):
        """Test TransactionsSummaryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
