# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.models.invoice_transaction_allocation import InvoiceTransactionAllocation

class TestInvoiceTransactionAllocation(unittest.TestCase):
    """InvoiceTransactionAllocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceTransactionAllocation:
        """Test InvoiceTransactionAllocation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceTransactionAllocation`
        """
        model = InvoiceTransactionAllocation()
        if include_optional:
            return InvoiceTransactionAllocation(
                transaction_id = 56,
                allocated_amount = 1.337
            )
        else:
            return InvoiceTransactionAllocation(
        )
        """

    def testInvoiceTransactionAllocation(self):
        """Test InvoiceTransactionAllocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
