# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.models.fiscalization_registration_request import FiscalizationRegistrationRequest

class TestFiscalizationRegistrationRequest(unittest.TestCase):
    """FiscalizationRegistrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiscalizationRegistrationRequest:
        """Test FiscalizationRegistrationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiscalizationRegistrationRequest`
        """
        model = FiscalizationRegistrationRequest()
        if include_optional:
            return FiscalizationRegistrationRequest(
                country = 'IT',
                name = 'Mario Rossi Albergo',
                tax_id = '98765432103',
                addresses = [
                    cloudbeds_fiscal_document.models.fiscalization_address.FiscalizationAddress(
                        street = 'Via Roma 123', 
                        number = '123', 
                        locality = 'Centro', 
                        region = 'Milan', 
                        state = 'MI', 
                        postal_code = '20121', 
                        country = 'IT', )
                    ],
                emails = [
                    cloudbeds_fiscal_document.models.fiscalization_email.FiscalizationEmail(
                        address = 'fatture@hotel-italia.it', 
                        label = 'Invoicing', )
                    ],
                phones = [
                    cloudbeds_fiscal_document.models.fiscalization_phone.FiscalizationPhone(
                        number = '+39 02 1234567', 
                        label = 'Office', )
                    ],
                identities = {"it-fiscal-code":"98765432103"},
                extensions = {"it-regime-fiscale":"RF07","it-sdi-format":"FPR12"}
            )
        else:
            return FiscalizationRegistrationRequest(
                country = 'IT',
                name = 'Mario Rossi Albergo',
        )
        """

    def testFiscalizationRegistrationRequest(self):
        """Test FiscalizationRegistrationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
