# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.models.fiscalization_consent_response import FiscalizationConsentResponse

class TestFiscalizationConsentResponse(unittest.TestCase):
    """FiscalizationConsentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiscalizationConsentResponse:
        """Test FiscalizationConsentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiscalizationConsentResponse`
        """
        model = FiscalizationConsentResponse()
        if include_optional:
            return FiscalizationConsentResponse(
                consented = True,
                consented_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                consented_by = ''
            )
        else:
            return FiscalizationConsentResponse(
                consented = True,
        )
        """

    def testFiscalizationConsentResponse(self):
        """Test FiscalizationConsentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
