# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.models.field_validation import FieldValidation

class TestFieldValidation(unittest.TestCase):
    """FieldValidation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldValidation:
        """Test FieldValidation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldValidation`
        """
        model = FieldValidation()
        if include_optional:
            return FieldValidation(
                pattern = '',
                min = 56,
                max = 56,
                checksum = True,
                format = ''
            )
        else:
            return FieldValidation(
        )
        """

    def testFieldValidation(self):
        """Test FieldValidation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
