# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.models.array_item_definition import ArrayItemDefinition

class TestArrayItemDefinition(unittest.TestCase):
    """ArrayItemDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArrayItemDefinition:
        """Test ArrayItemDefinition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArrayItemDefinition`
        """
        model = ArrayItemDefinition()
        if include_optional:
            return ArrayItemDefinition(
                type = 'object',
                fields = [
                    cloudbeds_fiscal_document.models.field_definition.FieldDefinition(
                        path = 'name', 
                        label = 'Legal Name', 
                        type = 'text', 
                        category = 'company', 
                        required = True, 
                        primary = True, 
                        validation = cloudbeds_fiscal_document.models.field_validation.FieldValidation(
                            pattern = '', 
                            min = 56, 
                            max = 56, 
                            checksum = True, 
                            format = '', ), 
                        data = cloudbeds_fiscal_document.models.field_data.FieldData(
                            placeholder = '', 
                            help = '', 
                            alternatives = [
                                ''
                                ], ), 
                        options = [
                            cloudbeds_fiscal_document.models.select_option.SelectOption(
                                value = '', 
                                label = '', )
                            ], 
                        item = cloudbeds_fiscal_document.models.array_item_definition.ArrayItemDefinition(
                            type = 'object', 
                            fields = [
                                cloudbeds_fiscal_document.models.field_definition.FieldDefinition(
                                    path = 'name', 
                                    label = 'Legal Name', 
                                    type = 'text', 
                                    category = 'company', 
                                    required = True, 
                                    primary = True, 
                                    properties = {
                                        'key' : 
                                        }, 
                                    default = null, 
                                    description = '', )
                                ], ), 
                        properties = {
                            'key' : 
                            }, 
                        default = null, 
                        description = '', )
                    ]
            )
        else:
            return ArrayItemDefinition(
                type = 'object',
                fields = [
                    cloudbeds_fiscal_document.models.field_definition.FieldDefinition(
                        path = 'name', 
                        label = 'Legal Name', 
                        type = 'text', 
                        category = 'company', 
                        required = True, 
                        primary = True, 
                        validation = cloudbeds_fiscal_document.models.field_validation.FieldValidation(
                            pattern = '', 
                            min = 56, 
                            max = 56, 
                            checksum = True, 
                            format = '', ), 
                        data = cloudbeds_fiscal_document.models.field_data.FieldData(
                            placeholder = '', 
                            help = '', 
                            alternatives = [
                                ''
                                ], ), 
                        options = [
                            cloudbeds_fiscal_document.models.select_option.SelectOption(
                                value = '', 
                                label = '', )
                            ], 
                        item = cloudbeds_fiscal_document.models.array_item_definition.ArrayItemDefinition(
                            type = 'object', 
                            fields = [
                                cloudbeds_fiscal_document.models.field_definition.FieldDefinition(
                                    path = 'name', 
                                    label = 'Legal Name', 
                                    type = 'text', 
                                    category = 'company', 
                                    required = True, 
                                    primary = True, 
                                    properties = {
                                        'key' : 
                                        }, 
                                    default = null, 
                                    description = '', )
                                ], ), 
                        properties = {
                            'key' : 
                            }, 
                        default = null, 
                        description = '', )
                    ],
        )
        """

    def testArrayItemDefinition(self):
        """Test ArrayItemDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
