# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.models.fiscalization_registration_status import FiscalizationRegistrationStatus

class TestFiscalizationRegistrationStatus(unittest.TestCase):
    """FiscalizationRegistrationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiscalizationRegistrationStatus:
        """Test FiscalizationRegistrationStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiscalizationRegistrationStatus`
        """
        model = FiscalizationRegistrationStatus()
        if include_optional:
            return FiscalizationRegistrationStatus(
                country_code = '',
                status = 'NOT_REGISTERED',
                provider_id = '',
                link_url = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                error = ''
            )
        else:
            return FiscalizationRegistrationStatus(
                country_code = '',
                status = 'NOT_REGISTERED',
        )
        """

    def testFiscalizationRegistrationStatus(self):
        """Test FiscalizationRegistrationStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
