# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.models.invoice_allocations_response import InvoiceAllocationsResponse

class TestInvoiceAllocationsResponse(unittest.TestCase):
    """InvoiceAllocationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceAllocationsResponse:
        """Test InvoiceAllocationsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceAllocationsResponse`
        """
        model = InvoiceAllocationsResponse()
        if include_optional:
            return InvoiceAllocationsResponse(
                allocations = [
                    cloudbeds_fiscal_document.models.invoice_transaction_allocation.InvoiceTransactionAllocation(
                        transaction_id = 56, 
                        allocated_amount = 1.337, )
                    ]
            )
        else:
            return InvoiceAllocationsResponse(
        )
        """

    def testInvoiceAllocationsResponse(self):
        """Test InvoiceAllocationsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
