# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.models.origin import Origin

class TestOrigin(unittest.TestCase):
    """Origin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrigin(self):
        """Test Origin"""
        # inst = Origin()

if __name__ == '__main__':
    unittest.main()
