# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from cloudbeds_fiscal_document.models.manual_recipient_request import ManualRecipientRequest
from cloudbeds_fiscal_document.models.recipient_request import RecipientRequest
from typing import Optional, Set
from typing_extensions import Self

class CreateSettlementInvoiceRequest(BaseModel):
    """
    CreateSettlementInvoiceRequest
    """ # noqa: E501
    user_id: Annotated[int, Field(strict=True, ge=0)] = Field(alias="userId")
    transaction_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Include transactions with the specified IDs (deprecated, use `includeTransactionIds` instead)", alias="transactionIds")
    folio_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Include all transactions from the specified folio IDs", alias="folioIds")
    exclude_transaction_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Exclude transactions with the specified IDs", alias="excludeTransactionIds")
    include_transaction_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Include transactions with the specified IDs", alias="includeTransactionIds")
    transaction_id_to_amount: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, description="Map of transaction ID to amount (in major currency units, e.g., 10.50 for $10.50) for partial transaction inclusion", alias="transactionIdToAmount")
    recipient: Optional[RecipientRequest] = None
    manual_recipient: Optional[ManualRecipientRequest] = Field(default=None, alias="manualRecipient")
    sequence_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, alias="sequenceId")
    due_date_property_timezone: Optional[date] = Field(default=None, alias="dueDatePropertyTimezone")
    __properties: ClassVar[List[str]] = ["userId", "transactionIds", "folioIds", "excludeTransactionIds", "includeTransactionIds", "transactionIdToAmount", "recipient", "manualRecipient", "sequenceId", "dueDatePropertyTimezone"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateSettlementInvoiceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of recipient
        if self.recipient:
            _dict['recipient'] = self.recipient.to_dict()
        # override the default output from pydantic by calling `to_dict()` of manual_recipient
        if self.manual_recipient:
            _dict['manualRecipient'] = self.manual_recipient.to_dict()
        # set to None if transaction_id_to_amount (nullable) is None
        # and model_fields_set contains the field
        if self.transaction_id_to_amount is None and "transaction_id_to_amount" in self.model_fields_set:
            _dict['transactionIdToAmount'] = None

        # set to None if sequence_id (nullable) is None
        # and model_fields_set contains the field
        if self.sequence_id is None and "sequence_id" in self.model_fields_set:
            _dict['sequenceId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateSettlementInvoiceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "userId": obj.get("userId"),
            "transactionIds": obj.get("transactionIds"),
            "folioIds": obj.get("folioIds"),
            "excludeTransactionIds": obj.get("excludeTransactionIds"),
            "includeTransactionIds": obj.get("includeTransactionIds"),
            "transactionIdToAmount": obj.get("transactionIdToAmount"),
            "recipient": RecipientRequest.from_dict(obj["recipient"]) if obj.get("recipient") is not None else None,
            "manualRecipient": ManualRecipientRequest.from_dict(obj["manualRecipient"]) if obj.get("manualRecipient") is not None else None,
            "sequenceId": obj.get("sequenceId"),
            "dueDatePropertyTimezone": obj.get("dueDatePropertyTimezone")
        })
        return _obj


