# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DocumentTriggerEvent(str, Enum):
    """
    DocumentTriggerEvent
    """

    """
    allowed enum values
    """
    MANUAL = 'manual'
    AT_CHECK_OUT = 'at_check_out'
    ON_RESERVATION_CREATED = 'on_reservation_created'
    ON_PAYMENT_CREATION = 'on_payment_creation'
    ON_ALLOCATION_CREATION = 'on_allocation_creation'
    UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DocumentTriggerEvent from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        """Handle unknown enum values by returning the unknown default case."""
        return cls.UNKNOWN_DEFAULT_OPEN_API

