# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cloudbeds_fiscal_document.models.field_data import FieldData
from cloudbeds_fiscal_document.models.field_definition_default import FieldDefinitionDefault
from cloudbeds_fiscal_document.models.field_validation import FieldValidation
from cloudbeds_fiscal_document.models.select_option import SelectOption
from typing import Optional, Set
from typing_extensions import Self

class FieldDefinition(BaseModel):
    """
    FieldDefinition
    """ # noqa: E501
    path: StrictStr = Field(description="Field path (e.g., \"name\", \"tax_id.code\", \"addresses\")")
    label: StrictStr = Field(description="Display label for the field")
    type: StrictStr = Field(description="Field input type")
    category: Optional[StrictStr] = Field(default=None, description="Field grouping category")
    required: StrictBool = Field(description="Whether field is required")
    primary: Optional[StrictBool] = Field(default=False, description="Indicates primary tax ID field")
    validation: Optional[FieldValidation] = None
    data: Optional[FieldData] = None
    options: Optional[List[SelectOption]] = None
    item: Optional[ArrayItemDefinition] = None
    properties: Optional[Dict[str, FieldDefinition]] = Field(default=None, description="Object properties for object type fields")
    default: Optional[FieldDefinitionDefault] = None
    description: Optional[StrictStr] = Field(default=None, description="Field description")
    __properties: ClassVar[List[str]] = ["path", "label", "type", "category", "required", "primary", "validation", "data", "options", "item", "properties", "default", "description"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum, returning unknown_default_open_api for unrecognized values"""
        _allowed_values = set(['text', 'email', 'select', 'boolean', 'array', 'object', 'unknown_default_open_api'])
        if value not in _allowed_values:
            return 'unknown_default_open_api'
        return value

    @field_validator('category')
    def category_validate_enum(cls, value):
        """Validates the enum, returning unknown_default_open_api for unrecognized values"""
        if value is None:
            return value

        _allowed_values = set(['company', 'tax', 'address', 'contact', 'supplementary', 'custom', 'unknown_default_open_api'])
        if value not in _allowed_values:
            return 'unknown_default_open_api'
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FieldDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of validation
        if self.validation:
            _dict['validation'] = self.validation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        # override the default output from pydantic by calling `to_dict()` of item
        if self.item:
            _dict['item'] = self.item.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in properties (dict)
        _field_dict = {}
        if self.properties:
            for _key_properties in self.properties:
                if self.properties[_key_properties]:
                    _field_dict[_key_properties] = self.properties[_key_properties].to_dict()
            _dict['properties'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of default
        if self.default:
            _dict['default'] = self.default.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FieldDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": obj.get("path"),
            "label": obj.get("label"),
            "type": obj.get("type"),
            "category": obj.get("category"),
            "required": obj.get("required"),
            "primary": obj.get("primary") if obj.get("primary") is not None else False,
            "validation": FieldValidation.from_dict(obj["validation"]) if obj.get("validation") is not None else None,
            "data": FieldData.from_dict(obj["data"]) if obj.get("data") is not None else None,
            "options": [SelectOption.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "item": ArrayItemDefinition.from_dict(obj["item"]) if obj.get("item") is not None else None,
            "properties": dict(
                (_k, FieldDefinition.from_dict(_v))
                for _k, _v in obj["properties"].items()
            )
            if obj.get("properties") is not None
            else None,
            "default": FieldDefinitionDefault.from_dict(obj["default"]) if obj.get("default") is not None else None,
            "description": obj.get("description")
        })
        return _obj

from cloudbeds_fiscal_document.models.array_item_definition import ArrayItemDefinition
# TODO: Rewrite to not use raise_errors
FieldDefinition.model_rebuild(raise_errors=False)

