# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cloudbeds_fiscal_document.models.fiscalization_address import FiscalizationAddress
from cloudbeds_fiscal_document.models.fiscalization_email import FiscalizationEmail
from cloudbeds_fiscal_document.models.fiscalization_phone import FiscalizationPhone
from cloudbeds_fiscal_document.models.fiscalization_registration_status import FiscalizationRegistrationStatus
from typing import Optional, Set
from typing_extensions import Self

class FiscalizationRegistrationResponse(BaseModel):
    """
    FiscalizationRegistrationResponse
    """ # noqa: E501
    country: Annotated[str, Field(strict=True)] = Field(description="ISO 3166-1 alpha-2 country code")
    name: StrictStr = Field(description="Legal name of the company")
    tax_id: Optional[StrictStr] = Field(default=None, description="Primary tax identification number", alias="taxId")
    addresses: Optional[Annotated[List[FiscalizationAddress], Field(min_length=1)]] = None
    emails: Optional[Annotated[List[FiscalizationEmail], Field(min_length=1)]] = None
    phones: Optional[List[FiscalizationPhone]] = None
    identities: Optional[Dict[str, StrictStr]] = Field(default=None, description="Additional tax/legal identities (key-value pairs)")
    extensions: Optional[Dict[str, StrictStr]] = Field(default=None, description="Country-specific tax configuration")
    property_id: StrictInt = Field(description="Property ID this registration belongs to", alias="propertyId")
    status: FiscalizationRegistrationStatus
    provider_id: Optional[StrictStr] = Field(default=None, description="Provider-specific ID (e.g., Invopop party ID)", alias="providerId")
    is_default: Optional[StrictBool] = Field(default=None, description="Whether this is the default fiscalization registration", alias="isDefault")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["country", "name", "taxId", "addresses", "emails", "phones", "identities", "extensions", "propertyId", "status", "providerId", "isDefault", "createdAt", "updatedAt"]

    @field_validator('country')
    def country_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Z]{2}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z]{2}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FiscalizationRegistrationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in addresses (list)
        _items = []
        if self.addresses:
            for _item_addresses in self.addresses:
                if _item_addresses:
                    _items.append(_item_addresses.to_dict())
            _dict['addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in emails (list)
        _items = []
        if self.emails:
            for _item_emails in self.emails:
                if _item_emails:
                    _items.append(_item_emails.to_dict())
            _dict['emails'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in phones (list)
        _items = []
        if self.phones:
            for _item_phones in self.phones:
                if _item_phones:
                    _items.append(_item_phones.to_dict())
            _dict['phones'] = _items
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FiscalizationRegistrationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "country": obj.get("country"),
            "name": obj.get("name"),
            "taxId": obj.get("taxId"),
            "addresses": [FiscalizationAddress.from_dict(_item) for _item in obj["addresses"]] if obj.get("addresses") is not None else None,
            "emails": [FiscalizationEmail.from_dict(_item) for _item in obj["emails"]] if obj.get("emails") is not None else None,
            "phones": [FiscalizationPhone.from_dict(_item) for _item in obj["phones"]] if obj.get("phones") is not None else None,
            "identities": obj.get("identities"),
            "extensions": obj.get("extensions"),
            "propertyId": obj.get("propertyId"),
            "status": FiscalizationRegistrationStatus.from_dict(obj["status"]) if obj.get("status") is not None else None,
            "providerId": obj.get("providerId"),
            "isDefault": obj.get("isDefault"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


