# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FiscalDocumentStatus(str, Enum):
    """
    Status of the fiscal document
    """

    """
    allowed enum values
    """
    COMPLETED = 'COMPLETED'
    VOIDED = 'VOIDED'
    PAID = 'PAID'
    PENDING_INTEGRATION = 'PENDING_INTEGRATION'
    PARTIALLY_PAID = 'PARTIALLY_PAID'
    COMPLETED_INTEGRATION = 'COMPLETED_INTEGRATION'
    FAILED_INTEGRATION = 'FAILED_INTEGRATION'
    CORRECTION_NEEDED = 'CORRECTION_NEEDED'
    CANCELED = 'CANCELED'
    CANCEL_REQUESTED = 'CANCEL_REQUESTED'
    OPEN = 'OPEN'
    REQUESTED = 'REQUESTED'
    VOID_REQUESTED = 'VOID_REQUESTED'
    FAILED = 'FAILED'
    MANUALLY_RECONCILED = 'MANUALLY_RECONCILED'
    REJECTED = 'REJECTED'
    ACCEPTED = 'ACCEPTED'
    PENDING_TRANSACTION = 'PENDING_TRANSACTION'
    ALLOCATED = 'ALLOCATED'
    UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FiscalDocumentStatus from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        """Handle unknown enum values by returning the unknown default case."""
        return cls.UNKNOWN_DEFAULT_OPEN_API

