# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FiscalizationRegistrationStatus(BaseModel):
    """
    FiscalizationRegistrationStatus
    """ # noqa: E501
    country_code: StrictStr = Field(description="ISO 3166-1 alpha-2 country code", alias="countryCode")
    status: StrictStr = Field(description="Registration status with government systems")
    provider_id: Optional[StrictStr] = Field(default=None, description="Provider-specific registration ID", alias="providerId")
    link_url: Optional[StrictStr] = Field(default=None, description="External link URL when status is AWAITING (e.g., government portal)", alias="linkUrl")
    created_at: Optional[datetime] = Field(default=None, description="When registration was created", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="When status was last updated", alias="updatedAt")
    error: Optional[StrictStr] = Field(default=None, description="Error if registration failed")
    __properties: ClassVar[List[str]] = ["countryCode", "status", "providerId", "linkUrl", "createdAt", "updatedAt", "error"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum, returning unknown_default_open_api for unrecognized values"""
        _allowed_values = set(['NOT_REGISTERED', 'PENDING', 'AWAITING', 'REGISTERED', 'FAILED', 'unknown_default_open_api'])
        if value not in _allowed_values:
            return 'unknown_default_open_api'
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FiscalizationRegistrationStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FiscalizationRegistrationStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "countryCode": obj.get("countryCode"),
            "status": obj.get("status"),
            "providerId": obj.get("providerId"),
            "linkUrl": obj.get("linkUrl"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "error": obj.get("error")
        })
        return _obj


